---
name: Encode-Wordlist-PGP
version: 1.1
author:
  - 'Earle Martin <hex@cpan.org>'
abstract: encode/decode hex values using the PGP Word List
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.8.0
provides:
  Encode::Wordlist::PGP:
    file: lib/Encode/Wordlist/PGP.pm
    version: 1.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
